WIP Hosts grid
preludeorg/build pull request #492
Opened 2023-02-01 18:24 UTC by mireaulf

- [ ] List icon is missing
- [ ] Not filtering data based on status
- [ ] Download not working
- [ ] List is not working
- [ ] Does not sort

2023-02-01 18:31 UTC, mireaulf commented
Good enough for PR?

2023-02-01 18:38 UTC, stephanwampouille requested changes

2023-02-01 18:38 UTC, stephanwampouille commented on apps/detect/src/components/hosts-grid/hosts-grid.module.css
> +    gap: 16px;
I think you're missing a margin of 1rem for the bottom of this

2023-02-01 18:38 UTC, stephanwampouille commented on apps/detect/src/components/hosts-grid/hosts-grid.module.css
> +    fill: #ffbf44;
not fully necessary but we have css variables for all of the fills and backgrounds if you want to switch to them or I can also help and do that

2023-02-01 18:38 UTC, stephanwampouille commented on apps/detect/src/components/hosts-grid/hosts-grid.tsx
> +                    List
missing list icon

2023-02-01 18:38 UTC, stephanwampouille commented on apps/detect/src/components/hosts-grid/hosts-grid.tsx
> +                <div className={styles.gridAction}>
You can also replace these with the <Button> component that we created but not fully necessary. I can help make the switch

2023-02-02 01:14 UTC, kenrick approved these changes

2023-02-02 01:14 UTC, merged