WIP decisions list
preludeorg/build pull request #493
Opened 2023-02-01 18:37 UTC by makk94

2023-02-01 22:12 UTC, stephanwampouille requested changes

2023-02-01 22:12 UTC, stephanwampouille commented on apps/detect/src/components/root.tsx
> +              <Popover className={styles.button}>
I would exchange this for the `<Button>` component instead, unless there is supposed to be an overlay that appears on click but I feel like it would make more sense to download on single click instead of being prompted. @NewMediaStudio thoughts?

2023-02-01 22:12 UTC, stephanwampouille commented on apps/platform/src/components/app.tsx
> -          <Header />
was this meant for the PR?

2023-02-01 22:12 UTC, stephanwampouille commented on apps/detect/src/components/root.tsx
> +            <Button className={styles.action} size={"tiny"} icon={<ChevronIcon/>} iconPosition={"right"}>
per Val's design the size should be `small`, we set that by default on this component so you can get rid of `size`

2023-02-01 22:12 UTC, stephanwampouille commented on apps/detect/src/components/root.tsx
> +                  <ServerIcon></ServerIcon>
not a big deal but typically if we have an element that doesn't have any content we can just close it by saying `<ServerIcon />`. You don't have to change, but just commenting on it

2023-02-01 23:13 UTC, makk94 commented on apps/detect/src/components/root.tsx
> +              <Popover className={styles.button}>
Mostly it just seemed easiest to style it the way that the other button is ha I shall try to switch it though

2023-02-01 23:23 UTC, makk94 commented on apps/platform/src/components/app.tsx
> -          <Header />
This was how i stopped the thing from asking if i wanted to log in every time it refreshed... assume this PR isn't actually going in as (gotta become its own component) is so just left it here to make development easier

2023-02-02 02:03 UTC, merged

2023-02-02 12:51 UTC, NewMediaStudio commented on apps/detect/src/components/root.tsx
> +              <Popover className={styles.button}>
In the future we might have other actions here so having a button makes sense (in our mockups it's a double button with a secondary pop over on the arrow click - not sure if we have that component yet:

![Feb-02-2023 07-51-13](https://user-images.githubusercontent.com/15107444/216329829-320f34b1-d0ca-4d61-9b29-27a7bcbfc425.gif)