feat: refactor decisions
preludeorg/build pull request #505
Opened 2023-02-02 17:53 UTC by stephanwampouille

2023-02-02 18:44 UTC, stephanwampouille commented
This PR refactors our decision details since it is being used in multiple locations in the app. I added an option to represent it vertically or horizontally and added decision item hover states. I also connected the overlay to the decision item.

2023-02-02 19:50 UTC, stephanwampouille commented
closes: #503

2023-02-03 05:25 UTC, kenrick requested changes

2023-02-03 05:25 UTC, kenrick commented on apps/detect/src/components/endpoint-overlay/endpoint-overlay.tsx
> +// import DecisionDetails from "../decision-overlay/decision-details";
You can just remove comments

2023-02-03 05:25 UTC, kenrick commented on apps/detect/src/components/endpoint-overlay/endpoint-overlay.tsx
> +      {/* <DecisionDetails actions="dropdown" forEndpoint={true} /> */}
same here

2023-02-03 05:25 UTC, kenrick commented on apps/detect/src/components/decision-overlay/decision-overlay.tsx
> +      {/* {actions === "dropdown" && (
same here

2023-02-03 05:25 UTC, kenrick commented on packages/ds/src/components/icons/time-icon.tsx
> +      fill="currentColor"
nice! we. should create a PR where we do this for all components

2023-02-03 15:08 UTC, stephanwampouille commented
@kenrick resolved comments, but lint will definitely complain. Those complaints will get resolved in through the other PR's

2023-02-03 17:22 UTC, merged