feat: new rule selector
preludeorg/build pull request #542
Opened 2023-02-07 21:19 UTC by stephanwampouille

I believe I got everything in besides the actual math for the details

<img width="1460" alt="Screenshot 2023-02-07 at 4 19 17 PM" src="https://user-images.githubusercontent.com/84744117/217368064-f4867aa9-7560-4e04-bc8a-f40b54fe261a.png">

2023-02-07 21:34 UTC, ceci21 commented on apps/detect/src/components/root.module.css
> +  display: row;
Do you mean `flex-direction: row`?

2023-02-07 23:49 UTC, stephanwampouille commented on apps/detect/src/components/root.module.css
> +  display: row;
yes! good catch, thanks!

2023-02-08 14:38 UTC, kenrick requested changes
Looks great! small changes then good to job

2023-02-08 14:38 UTC, kenrick commented on apps/detect/src/components/rule-selector/rule-selector.tsx
> +    suspense: false,
This is can be `suspense: true`

2023-02-08 14:38 UTC, kenrick commented on apps/detect/src/components/rule-selector/rule-selector.tsx
> +    suspense: false,
This way it loads the rules before showing the page

2023-02-08 14:54 UTC, kenrick approved these changes

2023-02-08 14:54 UTC, merged