hide export host data on loading
preludeorg/build pull request #676
Opened 2023-02-27 23:57 UTC by stephanwampouille

2023-02-27 23:59 UTC, kenrick requested changes

2023-02-27 23:59 UTC, kenrick commented on apps/detect/src/components/endpoint-overlay/endpoint-overlay.tsx
>          <Button
nit: I prefer using react to hide the button instead of css, easier to read imo

2023-02-28 00:00 UTC, stephanwampouille commented on apps/detect/src/components/endpoint-overlay/endpoint-overlay.tsx
>          <Button
reason I didn't do that is because of movement in the padding for the display, I can just hide it

2023-02-28 15:39 UTC, kenrick requested changes

2023-02-28 15:39 UTC, kenrick commented on apps/detect/src/components/endpoint-overlay/endpoint-overlay.module.css
> +
```suggestion
```

2023-02-28 15:53 UTC, merged